### ISSUE TITLE
FamilyParameter.Create update inputs for Dynamo 2.16

### ISSUE THREAD

**Issue by Lazarica-t** [erfajo/OrchidForDynamo#184]
### Is your feature request related to a problem? Please describe.

Hi, would it be possible to update the **FamilyParameter.Create** to make it work with the new build in Dynamo 2.16 nodes (**Parameter.SpecType**, **Parameter.GroupType**)? :D

I'm not sure if there is an easier way to extract the string .. 
![image](https://user-images.githubusercontent.com/49474519/215496846-6c61e345-3ee6-495e-b77c-e0dfdfbb64a4.png)
 
Best Regards!

**Comment by erfajo** [comment]
I should have updated that... do you have the latest build?

**Comment by Lazarica-t** [comment]
.8410? :D

![image](https://user-images.githubusercontent.com/49474519/215506449-0c377e10-00ab-4f88-a2ba-a37e67ac89fb.png)

**Comment by erfajo** [comment]
that is the right one... can you send the graph file?

**Comment by Lazarica-t** [comment]
Sure :D
[Family_copy_set_associate_parameters_from_nested.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/10537033/Family_copy_set_associate_parameters_from_nested.dyn.txt)

**Comment by erfajo** [comment]
it is strange... it is being caught at a odd place in the code... I need to dive into it.

But I can also see that you need a "SpecType.ToString" node, since that does not exist in the ootb nodes...

**Comment by erfajo** [comment]
I tried to see tried to see if it should be the grouptype that somehow was wrong... and to some extent it is, I dont know why the dynamoteam has choosen to return a string value that dosnt return the GroupType name...

Try to manually enter "Geometry" instead of "Dimensions" and it is working.
![image](https://user-images.githubusercontent.com/2844374/215663022-436b2478-b480-4f7b-a4d0-8c35f5ff846b.png)

the end of it is, that I must try to see into the dynamoteam node for SpecTypes and see if I can take the string value or I can make it accept their input value. Until then, please lookup the values for GroupTypes int the Revit API
https://www.revitapidocs.com/2023/a2fe7c6f-e5e2-bafe-23c8-819ba6a6c9b9.htm

**Comment by Lazarica-t** [comment]
Well it works if I manually add Strings for Type and category.
"SpecType.ToString" is this a node that exists in package or something ? :D

**Comment by erfajo** [comment]
I will code the nodes for that... I think something like SpecType.ToString and SpecType.ByName (and the same two for GroupType)
- Like I will make my nodes accept type input from SpecType/GroupType. However, it is first from the 216 versions it will work since the base class doesn't exist in previous versions.

**Comment by Lazarica-t** [comment]
Those nodes would be nice to have :D 
Yes, I know .. for older versions of Dynamo, the workflow in unchanged.

**Comment by erfajo** [comment]
ForgeTypes are a complete mess... to get the ForgeTypeId you must enter "Geometry", but the only thing you can return from the ForgeType is "Dimensions"... if this is the case with more forgetypes, then I must make a "translator", type for type. But this will take some time since I have to walk it true step by step :-S
This is badly made by the Revit Team. The Dynamo team is not to blame here...

**Comment by erfajo** [comment]
Well now the nodes are coded... now time for testing.
![Forge](https://user-images.githubusercontent.com/2844374/216251456-65d793ec-f47b-48c7-bd2f-8e0e24708088.png)

**Comment by Lazarica-t** [comment]
👍wow! that's awesome! waiting 🍿  for the new release to test 😸

**Comment by erfajo** [comment]
I have uploaded a new release...
[Forge.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/10581318/Forge.dyn.txt)
![Forge](https://user-images.githubusercontent.com/2844374/216670417-075e38ef-2dd5-4ca7-802c-8452083a7855.png)

**Comment by Lazarica-t** [comment]
Awesome! Tested it and it works now 🥳 
Great job!

**Comment by domil96** [comment]
Hi @erfajo ,
thank you for the great work on this.

Unfortunately, the ".Name" and ".ByName" nodes seem to work only in English. 
It seems that the SpecTypes and GroupTypes are translated according to the languages set by Revit/Dynamo.

In my case Revit is set to German. It seems that in Dynamo the language cannot be changed independently. Therefore Dynamo is also set to German in my case.

I have opened Revit in English for testing, everything works there. 
But in German, for example, it does not work:

![2023-02-06 09_24_00-Dynamo](https://user-images.githubusercontent.com/27489285/216923842-38986528-252b-4b08-817c-28785d7f018d.png)

Could you please take a look at it?
Thank you.

**Comment by erfajo** [comment]
That is probably correct.
It is a complete mess Autodesk has made with ForgeTypes, as an example can you see this in the API.
https://www.revitapidocs.com/2023/901adcef-5279-8855-f267-6bb1f53621ca.htm

However, the Dynamo team has chosen to use the label as their indicator, meaning that is the search string to use if you want to have some coherency between dynamo nodes and forgetypeids

Therefore, I had to make a json file with the conversion where I lookup the label and return the string I can convert to a proper typeId.

The Dynamo team has been forced to do as they do, since you cant lookup the name from its ForgeTypeId, you can only see the name when you call it (i.e. SpecType, GroupType, SymbolType)… we are literally left alone with a complete mess.

I can't solve it if this means that every localized version has other string values and can't be called with the English string values like it is the case with Microsoft Excel and other kinds of localized software.

I will try to see if any option is possible, if not, then I am afraid that I can't solve it unless you want to do the job by providing me the german version of all typeIds.

**Comment by domil96** [comment]
Maybe it would be easier if you could adjust the "FamilyParameter.Create" node so that it can be fed directly with ForgeTypeIds, as @Lazarica-t  actually wrote in the initial issue.
A conversion into strings is always a bit more problematic, as we have just discovered. (e.g. because of translation problems).

I noticed that the API method for "AddParameter" works with "ForgeTypeIds" anyway. Wouldn't it make sense to adapt the node accordingly?
Or at least create another variant so that there is one "FamilyParameter.Create" with String input and one "FamilyParameter.Create" with ForgeTypeId input for the parameter types and groups.

**Comment by erfajo** [comment]
That is also on my to-do list, and I am testing it for familyparameter.create at the moment. However, taking that step is much more complicated since anything using typeIds needs to be converted... and it is only applicable for 2023 versions and beyond. For any version before 2023 can this conversion not be implemented. 

This is a problem and it will take me some while before I can change/implement all the cases with typeIds can be used. I am sure that this issue must occur for many codes around the world where localized versions will meet a wall.

I will try once more to see if Autodesk somehow has released something concerning ForgeTypes where we can look up localized names… when I have some available time for it.

**Comment by erfajo** [comment]
Good news... it is not that difficult to change the nodes, but it takes some time to make sample files... first screendump attached :-)
![AddConvert](https://user-images.githubusercontent.com/2844374/217319950-0df67263-0ca6-4c6c-bbcb-b581421faf40.png)

**Comment by erfajo** [comment]
It takes too long time for me to fix all samplefiles for Revit2023/Dynamo 2.16, so I have released the version that takes Dynamo specType and GroupType... now I can continue makeing all the remaning sample files in my own pace :-)

**Comment by Lazarica-t** [comment]
@erfajo were the **GroupType , SpecType** drop down nodes removed ? 😕 
**GroupType** is still present in the latest version, but not working.
And **SpecType** missing all togheter.
![image](https://user-images.githubusercontent.com/49474519/221526463-576772d5-b187-4457-8ad1-b459d9b2c1d7.png)

**Comment by erfajo** [comment]
No, it is not... BUT in dynamo 2.16 dropdown nodes **only** work if at least one item exists... This is a bug, but I can't do anything about it. I hope it will be fixed by the dynamo team in the next release, like other errors that exist in the 2.16 version.
Many of my sample graphs for dynamo 2.16 (+2.13) I have created ran into this problem over and over again, worst is, that many of my dropdown nodes simply got deleted if not at least one item that uses at given dropdown exists... really annoying :-S

**Comment by Lazarica-t** [comment]
OMG.. found them 😖 , the Dynamo search is really bad.
FamilyDocument.Current is working for me :D in the vs 5805.
