### ISSUE TITLE
FamilyType.Current Operation Failed. A serious issue has occured please contact author of the package.

### ISSUE THREAD

**Issue by akrcoceo** [erfajo/OrchidForDynamo#226]
### Operating system
(Windows 11)

### Revit and Dynamo version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 2024.2
Dynamo: 2.19.3
Orchid: 6119

### What did you do? 
Added FamilyType.Current to my workspace

### What did you expect to see?
the node placed with no issue

### What did you see instead?
an error popup (little yellow triangle) and the node producing a null readout. This is also happening for formula.set
![Screenshot 2024-01-12 105837](https://github.com/erfajo/OrchidForDynamo/assets/156456745/55a066f1-7c2b-4a3b-a1fb-b1a6239c1560)
![Screenshot 2024-01-12 105136](https://github.com/erfajo/OrchidForDynamo/assets/156456745/489ff926-3162-4210-ba3a-fd3752875814)
![Screenshot 2024-01-12 090013](https://github.com/erfajo/OrchidForDynamo/assets/156456745/94fbf474-5d32-4e25-a6cd-d24a20fb0777)

**Comment by erfajo** [comment]
This is the second error message I have gotten since I did a larger internal update. Unfortunately did the other not return what could have happened since they/he apparently solved the issue without informing me what caused the error. Which means that this issue starts at square one :-S

First of all, I can see that you have not the IFC exporter installed. You have only the build-in version. You can get the latest build of the IFCexporter here --> https://github.com/Autodesk/revit-ifc/releases

Next, it looks like there could be an issue with System.Collections.Immutable, I am not sure that this should cause any error, since this has been a system assembly that the dynamo team has control over since version 2.1, at least the last five years, but I will look into that.

Just for searching possible problems, which other packages do you load?

**Comment by akrcoceo** [comment]
The IFC exporter took away the build error for library and the system collections, but im still getting the serious issue error. 
These are the packages i have installed.
![image](https://github.com/erfajo/OrchidForDynamo/assets/156456745/43173de5-c9a6-4c1f-a63e-1305c4932945)

**Comment by erfajo** [comment]
I am pretty sure it is not Clockwork or Rhythm that causes any error, I will presume the same about Crumple but since I do not use any other packages than my own it will be a guess. I will not presume that any Dynamoteam package is a threat, but I don't know.

It leaves the DynamoPlayerExtension, what is that, and who makes it!? A fast test is to unload that and try to restart Revit/Dynamo. 
The longer test is to check if a dynamo assembly is included in a ”bin” folder (or in any other package for that sake). If a Dynamo assembly is included, it will cause problems and most certainly something not to have.

The full test is to unload all packages except Orchid, then start Revit/Dynamo, check if it catches an error… then redo that test when adding a package at the time. As mentioned, I don't presume that Clockwork and Rhythm will cause any error, but from there I am unsure.

**Comment by akrcoceo** [comment]
I have disabled all of the packages except Orchid and still getting the error, and its only occurring specific nodes. I have quite a few in this graph and only familydocument.current and Formula.set are causing the error. The new version did not resolve my issue either. 
![image](https://github.com/erfajo/OrchidForDynamo/assets/156456745/43eacdc4-9707-47be-8199-4e161d7afc6d)

**Comment by erfajo** [comment]
this i very strange...
however, could it be the case that you use a version of Revit that is not English?
I have had such a kind of issue with the Russian language version of Revit. That means also that I have a starting point for error searching…

**Comment by erfajo** [comment]
I have now tried to add some checks for language... I have uploaded a beta build, can you test that?
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/ad1403c7-da4f-4412-9e13-697e7a6c37d5)

**Comment by erfajo** [comment]
I will close this issue due to no response. I hope the issue is solved.

**Comment by akrcoceo** [comment]
Hi sorry for late response, i am using english version of revit, and the beta build did not solve my issue. Any other thoughts?

**Comment by erfajo** [comment]
The current build should do it, but if you still have an issue then please follow up so I know that you still have the problem. Otherwise do I not have any clue if the issue is solved or not!

I can see from your screen dumps that you use German language parameters, could it be the case that your Windows version is in German? I am Danish, and my Windows is in Danish and I use Revit in English… So I cannot see why it should play any role to have different languages… but just to know all the factors I am dealing with.

If you still have the error, then I need to know which other packages you have, and please once more post the error messages as you did previously. I hope that some of the previous errors have disappeared.
